### ISSUE TITLE
rotation matrix returned not in SO(3)

### ISSUE THREAD

**Issue by cfreundlich** [royxue/ippe_py#2]
The code runs fine, but both of our solutions R1 and R2 are reflections, i.e., they are orthogonal but have -1 determinant.  The translation vectors look correct.  Could this be because IPPE thinks we are looking at the planar object from behind?  If this is the problem, how do we enforce the front-facing constraint? If not, what could it be?

**Comment by tobycollins** [comment]
That is strange because the algorithm should enforce R1 and R2 are rotations. Can you please email me the input data (model points and normalized image points), and I will cross-check with the Matlab implementation. 
Thanks, Toby

**Comment by cfreundlich** [comment]
Hi Toby -- I just sent an email to the gmail account listed on page 1 of the IPPE paper that I downloaded from arxiv.  
-Charlie

**Comment by tobycollins** [comment]
Hi Charlie,

nice to hear from you and the kind words. I'm glad you're finding this work
useful. I'm just on my way home now. I know exactly what this is about. For
now, can you just run IPPE using 2D model points (a 2xN vector of model
points). You should do this when the model points are on the plane z=0.
It's quicker because there is no 3x3 SVD computation. If you do this, all
should be fine. I'll message you with the fix to ensure the problem you had
does not occur.

And I'm a big fan of Tesla!

Best regards, Toby



Le 23 mars 2017 6:01 PM, "cfreundlich" <notifications@github.com> a écrit :

Hi Toby -- I just sent an email to the gmail account listed on page 1 of
the IPPE paper that I downloaded from arxiv.
-Charlie

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/royxue/ippe_py/issues/2#issuecomment-288788419>, or mute
the thread

**Comment by cfreundlich** [comment]
Now the matrices are in SO(3).  Thanks!

**Comment by royxue** [comment]
Solved.
Issue closed ;)
